### ISSUE TITLE
Change to professional

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#1]
Change to professional only by using HTML, CSS, and JS. 
please do not use any framework.

**Comment by ELIJAHJOHNNY** [comment]
Hello Minhaj! Please, I would really love to contribute to this project. Thank you in advance for your reply.

**Comment by minhaj-313** [comment]
yeah you can do it

**Comment by Adeku5080** [comment]
Hey,I will Love to take up this issue

**Comment by Sushie611** [comment]
hello sir could you please assign me the work

**Comment by minhaj-313** [comment]
Yes, you can do it

**Comment by minhaj-313** [comment]
> Hey,I will Love to take up this issue

Yeah, then start

**Comment by minhaj-313** [comment]
> hello sir could you please assign me the work

yes, you can do it

**Comment by minhaj-313** [comment]
> Hello Minhaj! Please, I would really love to contribute to this project. Thank you in advance for your reply.

your Welcome, You can do it
