### ISSUE TITLE
Find Bugs and Resolved it

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#17]

**Comment by Srinja333** [comment]
i want to know, what type of problem are  you facing??

**Comment by Zaynabnadada** [comment]
Is it a bug in a code?

**Comment by minhaj-313** [comment]
> Is it a bug in a code?

Find it or Resolve the problem of anything which is not properly set

**Comment by rushikesh1799** [comment]
Hi Minhaj, 

I was going through your portfolio, it looks quite fantastic now. However, I could not find your linktree link page in My Intro page, Services page, Blog page and Contact Me page.

I think for navigation purposes it's important to have that linktree page on every page.

I have already Star this repo, followed you, and contributed before, Can you please assign this to me So that I can make changes and submit PR?

eg.
![image](https://user-images.githubusercontent.com/68096217/194091760-63ad7636-e5ec-401e-abc2-90938821f585.png)

**Comment by minhaj-313** [comment]
> Hi Minhaj,
> 
> I was going through your portfolio, it looks quite fantastic now. However, I could not find your linktree link page in My Intro page, Services page, Blog page and Contact Me page.
> 
> I think for navigation purposes it's important to have that linktree page on every page.
> 
> I have already Star this repo, followed you, and contributed before, Can you please assign this to me So that I can make changes and submit PR?
> 
> eg. ![image](https://user-images.githubusercontent.com/68096217/194091760-63ad7636-e5ec-401e-abc2-90938821f585.png)

Yes start doing bro

**Comment by minhaj-313** [comment]
> hey can you assign it to me, i may find and fix bugs present in it

yeah sure.
But first you need to give star to this repository and follow me then start and please do quality code.
Thank You.

**Comment by rushikesh1799** [comment]
Hi Manhaj, 

There is another one small bug I can configure in the intro page compared to all other pages in the sidebar.

For eg., all the page's sidebar has the same styling whereas it is different for the intro page.

Images:

Home page:
![image](https://user-images.githubusercontent.com/68096217/194125395-937f8723-d7b1-47e2-82ec-d398305f281f.png)

intro page:
![image](https://user-images.githubusercontent.com/68096217/194125580-e36edc1a-5054-4ea2-bae3-c0290ae933cf.png)

As you can see in the above screenshots styling is unmatched. (like font-style, font-family also hover effect)

Please check the screenshots and let me know if can I go ahead and make changes and submit PR?

**Comment by minhaj-313** [comment]
> Hi Manhaj,
> 
> There is another one small bug I can configure in the intro page compared to all other pages in the sidebar.
> 
> For eg., all the page's sidebar has the same styling whereas it is different for the intro page.
> 
> Images:
> 
> Home page: ![image](https://user-images.githubusercontent.com/68096217/194125395-937f8723-d7b1-47e2-82ec-d398305f281f.png)
> 
> intro page: ![image](https://user-images.githubusercontent.com/68096217/194125580-e36edc1a-5054-4ea2-bae3-c0290ae933cf.png)
> 
> As you can see in the above screenshots styling is unmatched. (like font-style, font-family also hover effect)
> 
> Please check the screenshots and let me know if can I go ahead and make changes and submit PR?

Yes Go Ahead, Great work bro  👍
