### ISSUE TITLE
Link all Pages Properly

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#19]
Link all Pages Properly and all Social handles properly and find some extra bugs as well.

**Comment by manipta** [comment]
i want to work on it

**Comment by minhaj-313** [comment]
Sure

**Comment by manipta** [comment]
> Link all Pages Properly and all Social handles properly and find some extra bugs as well.

Pls assign me this issue

**Comment by manipta** [comment]
thanks :)

**Comment by minhaj-313** [comment]
done

**Comment by manipta** [comment]
hey, should I put the respective icons of social media too?
![image](https://user-images.githubusercontent.com/72307020/193448622-e9ca7cbc-4e92-4528-a9bf-a391e2b3d233.png)

**Comment by manipta** [comment]
@minhaj-313

**Comment by minhaj-313** [comment]
> @minhaj-313

Yes You Can

**Comment by manipta** [comment]
> > @minhaj-313
> 
> Yes You Can

i was done with that.
![image](https://user-images.githubusercontent.com/72307020/193450025-216280f7-4de3-4745-a2e2-0bcc66993eb7.png)

do u need it here or I can remove them
![image](https://user-images.githubusercontent.com/72307020/193450057-0ef87990-0aeb-4b5e-8cd1-47eb3411fa66.png)

**Comment by manipta** [comment]
only social media part @minhaj-313

**Comment by minhaj-313** [comment]
but icons are not proper

**Comment by manipta** [comment]
> but icons are not proper

is it okay for first image?

**Comment by minhaj-313** [comment]
Yes
