### ISSUE TITLE
Contribute for Hacktoberfest

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#2]

**Comment by destroyer5067** [comment]
What exactly we need to do?

**Comment by minhaj-313** [comment]
> What exactly we need to do?

Do something attractive add some animations or change some mobile responsiveness or etc,  Please make sure do Quality PR for accepting in Hacktoberfest. 
Firts you need to give Star to this Repository >> Then Fork the Repository >> Clone it >> Do quality Code >> Make Your PR.....
Thank You

**Comment by yogitha02** [comment]
@minhaj-313 Hey ! I would like to work on this , please do assign me

**Comment by minhaj-313** [comment]
Great, Then Start doing. But Make Sure Write very clean code

**Comment by minhaj-313** [comment]
@yogitha02 First you need to give Star to this Repository >> Then Fork the Repository >> Clone it >> Do quality Code >> Make Your PR.....
Thank You

**Comment by antomuangigitau** [comment]
hello,could you please assign this to me

**Comment by minhaj-313** [comment]
> hello,could you please assign this to me

yeah, Start doing.
