### ISSUE TITLE
Add a CONTRIBUTING.md file with contribution guidelines to your repository.

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#21]

**Comment by bloodmonk7** [comment]
I would like to do this, can you assign it to me?

**Comment by minhaj-313** [comment]
> I would like to do this, can you assign it to me?

Thanks bro, Yes you can do it

**Comment by Samriddh2703** [comment]
can you assign me please

**Comment by minhaj-313** [comment]
> can you assign me please

Yes you can start
first you need to give star to this repository and follow me then start doing as per hacktoberfest rule for more information you can read contributer.md file Thank You
