### ISSUE TITLE
Add Toggle Button in Mobile Responsive 

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#22]

**Comment by trishit-char** [comment]
Can I work with this issue?

**Comment by minhaj-313** [comment]
> Can I work with this issue?

Yes

**Comment by Harshdeep-Yadav** [comment]
can i work on it

**Comment by minhaj-313** [comment]
> can i work on it

Yes you can start.
First, you need to give start to this repository and follow me >> Fork this Repositor >> Then clone it >> do quality code >> Make PR.
Thank You
