### ISSUE TITLE
Add Background Animation

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#23]

**Comment by NAMANIND** [comment]
what kind of animation did you want to add?

**Comment by minhaj-313** [comment]
As your Wish any attractive

**Comment by piyush-sri** [comment]
I would like to work on this issue.

**Comment by minhaj-313** [comment]
> I would like to work on this issue.

Yes you can

**Comment by piyush-sri** [comment]
I had added animation in background and open a pull request please have a look.
