### ISSUE TITLE
Add mailto to href instead of email as URL

### ISSUE THREAD

**Issue by soham-pagi** [minhaj-313/Portfolio-1#27]
![image](https://user-images.githubusercontent.com/60569648/193452451-e618209e-7f64-4d08-be91-bf70074a69dd.png)

**Comment by soham-pagi** [comment]
I would like to do this, can you assign it to me?

**Comment by minhaj-313** [comment]
yes but, it not acceptable in hacktoberfest. You need to do more customizations add some CSS. Then I will merge your PR

**Comment by soham-pagi** [comment]
Yes sure, I will do some customization, thanks
