### ISSUE TITLE
Add Attractive Blog Card design and also change font-family.

### ISSUE THREAD

**Issue by Ksj14-kumar** [minhaj-313/Portfolio-1#30]

**Comment by minhaj-313** [comment]
Yes This is also one work, You can Make it.

**Comment by Ksj14-kumar** [comment]
Will Hacktoberfest accept this?

**Comment by Ksj14-kumar** [comment]
Can I use tailwind CSS only for blog.html?

**Comment by minhaj-313** [comment]
> Can I use tailwind CSS only for blog.html?

No brother sorry for That because this is only with HTML, CSS, JS, No any Framework or Library.
You can try in HTML,CSS,js code

**Comment by Ksj14-kumar** [comment]
okay,  I do this on these technologies.

**Comment by minhaj-313** [comment]
> okay, I do this on these technologies.

Great, Try Your Best Bro...
