### ISSUE TITLE
Need to add Code_of_Conduct.md File.

### ISSUE THREAD

**Issue by piyush-sri** [minhaj-313/Portfolio-1#31]
I would like to work on this issue by adding Code_of_Conduct.md file in your repo.

**Comment by minhaj-313** [comment]
ok sure

**Comment by abhicalyptic** [comment]
Hey, Is this issue still unfinished?
I will like to add code of conduct file and complete it, assign me this.
Also add the labels :)

**Comment by minhaj-313** [comment]
> Hey, Is this issue still unfinished? I will like to add code of conduct file and complete it, assign me this. Also add the labels :)

go for another issue this is already done @abhicalyptic

**Comment by abhicalyptic** [comment]
okay, thanks :)

**Comment by abhicalyptic** [comment]
Can you please close all the issues which are completed? It is pretty confusing now.

**Comment by minhaj-313** [comment]
> Can you please close all the issues which are completed? It is pretty confusing now. @minhaj-313

ok thanks for suggestion.
