### ISSUE TITLE
Hamburger menu has a separate close icon

### ISSUE THREAD

**Issue by pexeixv** [minhaj-313/Portfolio-1#33]
Normally, we see that the hamburger icon doubles up as the close icon. However, here there are two separate buttons. If the ≡ icon is clicked when the navigation is expanded, it serves no purpose. This is bad UX.
If you feel this is a valid issue, assign it to me and I will fix it under Hacktoberfest.

![image](https://user-images.githubusercontent.com/68476117/193460933-f8302106-10a3-48c4-b779-7443aa6ced10.png)

**Comment by minhaj-313** [comment]
Yeah Great, You Can do it.
