### ISSUE TITLE
Add Animation on side navbars while hover mouse

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#38]

**Comment by akshatjainei** [comment]
I would like to be assigned for this issue

**Comment by minhaj-313** [comment]
Yes Start.
first you need to give star to this repository and follow me then start doing as per hacktoberfest rule for more information you can read contributer.md file Thank You

**Comment by kirtiraj22** [comment]
@minhaj-313  bro can you assign it to me?
cause i have already forked this repo and made a **bottom underline hover effect** and its ready.
so can i create a pull request?

**Comment by minhaj-313** [comment]
> @minhaj-313 bro can you assign it to me? cause i have already forked this repo and made a **bottom underline hover effect** and its ready. so can i create a pull request?

Yes you can.
