### ISSUE TITLE
Hamburger Not working in some pages 

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#39]

**Comment by amin-deraiya** [comment]
Can I work on this?

**Comment by minhaj-313** [comment]
Yeah Sure start doing 
first you need to give star to this repository and follow me then start doing as per hacktoberfest rule for more information you can read contributer.md file Thank You

**Comment by amin-deraiya** [comment]
should I've to fork the main branch because I can't see the hacktoberfest branch ?

**Comment by minhaj-313** [comment]
> @minhaj-313 should I've to fork the main branch because I can't see the hacktoberfest branch ?

yeah ok
