### ISSUE TITLE
Test Typing Animation in Home Page

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#44]
Add this 👍 

- Full Stack Developer
- Frontend Developer
- Backend Developer
- Web Developer & Designer
- Freelancer
- Open Source Contributer

**Comment by LemonDrop847** [comment]
Hey, Can I work on this? @minhaj-313

**Comment by raj-hero** [comment]
@minhaj-313 where are these to be added. Can you elaborate

**Comment by minhaj-313** [comment]
> @minhaj-313 where are these to be added. Can you elaborate

add it at home page

**Comment by raj-hero** [comment]
> > @minhaj-313 where are these to be added. Can you elaborate
> 
> add it at home page

assign me

**Comment by raj-hero** [comment]
issue #44 commited by me. pull request #54.Mention issues if found any. Also, do add hacktoberfest-accepted tag if no issues are found.

**Comment by raj-hero** [comment]
> issue #44 commited by me. pull request #54.Mention issues if found any. Also, do add hacktoberfest-accepted tag if no issues are found.

@minhaj-313

**Comment by raj-hero** [comment]
@minhaj-313 index.html file for issue #44 is commited by me in pull request #54. Mention the issues if found any. Also, do add hacktoberfest-accepted tag if no issues are found.

**Comment by minhaj-313** [comment]
ok
