### ISSUE TITLE
Make it Mobile Responsive 

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#46]

**Comment by Skysparko** [comment]
hey, @minhaj-313 can I work on it?

**Comment by minhaj-313** [comment]
Yes,
first you need to give star to this repository and follow me then start doing as per hacktoberfest rule for more information you can read contributer.md file Thank You

**Comment by Skysparko** [comment]
done i followed you also give star to this repo

**Comment by minhaj-313** [comment]
> done i followed you also give star to this repo

Thank you
