### ISSUE TITLE
Portfolio-1 - Hacktoberfest 2022 

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#5]
What exactly do we need to do? Do something attractive add some animations or change some mobile responsiveness or etc, Please make sure to do Quality PR for accepting in Hacktoberfest. 
First, you need to give start to this repository then >> Fork this Repositor >> Then clone it >> Make quality Project >> Make PR.
Thank You

**Comment by tanmay-S12** [comment]
Will you pls elaborate on exactly what needs to be done?

**Comment by minhaj-313** [comment]
cange its to responsive or change something in other pages which looks attractive or you can do anything but make sure do quality code. and send ScreenShot of your work then make PR then you will get merged in this Repository as Accepted Hactoberfest label

**Comment by tanmay-S12** [comment]
In the contribution guidelines, you mentioned cloning the repository from the "hactoberfest" branch. But there is only one "main" branch. Should I continue to clone it from the main branch?

**Comment by minhaj-313** [comment]
> In the contribution guidelines, you mentioned cloning the repository from the "hactoberfest" branch. But there is only one "main" branch. Should I continue to clone it from the main branch?

Yes

**Comment by sanketdisale871** [comment]
I want to work on this issue. Can you assign to me . @minhaj-313

**Comment by minhaj-313** [comment]
@sanketdisale871 
Yes you can start.
First, you need to give start to this repository and follow me >> Fork this Repositor >> Then clone it >> do quality code >> Make PR.
Thank You

**Comment by tanmay-S12** [comment]
@minhaj-313 hey, Thanks for giving me the opportunity, but unfortunately I am able to work on it. Sorry for any inconvenience caused.

**Comment by coderboy-yash** [comment]
hey,
I am interested in working on this issue  please assign this issue to me  @minhaj-313

**Comment by minhaj-313** [comment]
> hey, I am interested in working on this issue please assign this issue to me @minhaj-313

@coderboy-yash  Yes you can start doing.
First you neet to give star to this repository and follow me, Thank You

**Comment by coderboy-yash** [comment]
thanks for assigning me this issue
