### ISSUE TITLE
Add GitHub Social icon in All pages 

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#55]
Add GitHub Social icon in All pages, very easy task for beginners

**Comment by Harsh8084** [comment]
@minhaj-313 Can you please assign me the task

**Comment by Chaitanya-087** [comment]
hi! can you assign me this issue

**Comment by minhaj-313** [comment]
> 

Start doing.  @Chaitanya-087 
first you need to give star to this repository and then follow me and start doing and please follow proper rules of hacktoberfest.
Thank You

**Comment by minhaj-313** [comment]
@Utkarsh212 and @bloodmonk7  you can see another issue

**Comment by Chaitanya-087** [comment]
@minhaj-313  
gave star
and followed you
sent a pr

**Comment by minhaj-313** [comment]
> @minhaj-313 gave star and followed you sent a pr

merged your PR successfully

**Comment by mak650650** [comment]
is this is closed

**Comment by minhaj-313** [comment]
> is this is closed

yes, try another issue
