### ISSUE TITLE
Add Preloader to all pages 

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#65]
## Add preloader to [Portfolio-1](https://github.com/minhaj-313/Portfolio-1) 
Read all Rules from contributing.md before starting.
First you need to give star to this repository then follow me and then start working on this project. please do quality and clean code.
Thank You.

**Comment by yash-sharma13** [comment]
assign this to me please

**Comment by minhaj-313** [comment]
@yash-sharma13 I assigned you Please Start doing.
Firts give the star to this repository and follow me and the you can start and do quality code. Thank You.

**Comment by yash-sharma13** [comment]
i have successfully resolved the issue. i have starred this repository and followed you as well.. thank you for giving me this opportunity.
please close this issue now.

**Comment by minhaj-313** [comment]
> i have successfully resolved the issue. i have starred this repository and followed you as well.. thank you for giving me this opportunity. please close this issue now.

Thank You So Much
