### ISSUE TITLE
Fix the issue of hamburger and add it same in all pages - Hacktoberfest

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#66]

**Comment by dinesh-07** [comment]
Assign this to me

**Comment by melencholicmice** [comment]
hello , i would like to take up this issue

**Comment by Manujdixit** [comment]
Hey @minhaj-313 I would like to work on this issue. Please assign it to me.

**Comment by minhaj-313** [comment]
@dinesh-07 I am assigning to you please do quality code.
First you need to give star to this repository and then follow me then you can start and please follow all the hacktoberfest guideline.

**Comment by yash-sharma13** [comment]
Hey i can do this one.. assign this to me  please

**Comment by yash-sharma13** [comment]
Hey i have resolved this issue. The pr is merged now you can close this issue.
Thanks for giving me the opportunity.
