### ISSUE TITLE
Improve Services Section

### ISSUE THREAD

**Issue by AryanSahoo-2003** [minhaj-313/Portfolio-1#68]
Hey!! I wanted to improve the services section by creating flexbox and storing all that in a card slider type U.I..
Can you assign it to me under hacktoberfest 2022?

**Comment by minhaj-313** [comment]
@AryanSahoo-2003  You can start working first you need to give star to this repository and follow me then you can start and please do quality code.

**Comment by shaikhhafeez** [comment]
I want to contribute in this issue
