### ISSUE TITLE
Add an  Animation on Mouse Cursor

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#7]

**Comment by GyaneshwarTiwari** [comment]
I would like to animate buttons and improve social icon buttons.
Can you tell me what is meaning of issue to be assigned to someone. Is it different from forking and then doing pull request.

**Comment by minhaj-313** [comment]
if assign you then you can work on this issue ( this is mean of your question ) 
apart from that you can work on this project but make sure do code very clean and make attractive.

Steps : First you need to give Star to this Repositor >> then fork >> Then Clone >> Make changes in Project but In quality Way >> Then make PR >> and send ScreeShot as well.
Thank You

**Comment by 20RitikSingh** [comment]
I want to work on this, can you please describe where you want mouse animation?

**Comment by minhaj-313** [comment]
Yes you can work,
can you change normal mouse cursor to animated cursor
