### ISSUE TITLE
enhancement in buttons

### ISSUE THREAD

**Issue by Anjuli08** [minhaj-313/Portfolio-1#71]
I want to improve excess padding in the buttons as they appear to be unnecessarily large, under HACKTOBERFEST'22

**Comment by minhaj-313** [comment]
Yes you can start working on it

**Comment by Anjuli08** [comment]
> Yes you can start working on it

I've already created a pr! pls review it under Hacktoberfest

**Comment by minhaj-313** [comment]
Thank You @Anjuli08
