### ISSUE TITLE
[BUG] Section moves when user hovers over icons

### ISSUE THREAD

**Issue by abitsalihu** [minhaj-313/Portfolio-1#78]
The whole `devInfo` text section moves when the user hovers over the `icon-socials`.

The `bug` was tested in `Google Chrome` and `Safari`.

I would like to be assigned so I can contribute and help with this issue. :)

Below is a video of the `bug`, please pay attention at the `devInfo` text when the user hovers over the `icons` : 

https://user-images.githubusercontent.com/94648837/195529524-cf7d6257-f6e7-4912-903b-6df4297597c4.mov

**Comment by minhaj-313** [comment]
@abitsalihu  Great, You can Start doing.
First you need to give star to this repository and follow me then start doing work
Thank You.
