### ISSUE TITLE
Add Attractive Footer

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#8]

**Comment by shivam-bhadani** [comment]
I can add footer to the website please assign me this issue

**Comment by minhaj-313** [comment]
> I can add footer to the website please assign me this issue

Yes you can Start, Make Sure it is in quality way, write code in quality, 
Steps: !st make Star to this Repository >> Then Fork it >> Clone it >> Add Footer and Customize code >> Then make PR >> Send me Screen Shot also.

Thank You For participating.

**Comment by shivam-bhadani** [comment]
What sections do you need in the footer please provide a little detail about the structure of footer

**Comment by minhaj-313** [comment]
> What sections do you need in the footer please provide a little detail about the structure of footer

Add some social icons , Copyright , pages but add it css also for animation 
As Your Wish Try Your Best Bro

**Comment by shivam-bhadani** [comment]
@minhaj-313 Created pull request please review and merge it
