### ISSUE TITLE
Hover Effect in Sidebar or Navbar

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Portfolio-1#9]

**Comment by amitmishra11** [comment]
@minhaj-313 I would like to work on this

**Comment by flow6979** [comment]
hi @minhaj-313 can i contribute to this repository?
thank you

**Comment by minhaj-313** [comment]
> @minhaj-313 I would like to work on this

Yes You Can Start

**Comment by minhaj-313** [comment]
> hi @minhaj-313 can i contribute to this repository? thank you

You can Start doing

**Comment by minhaj-313** [comment]
@amitmishra11 @flow6979   
Steps: 1st make Star to this Repository >> Then Fork it >> Clone it >> Add Footer and Customize code >> Then make PR >> Send me Screen Shot also.

**Comment by amitmishra11** [comment]
> @amitmishra11 @flow6979 Steps: 1st make Star to this Repository >> Then Fork it >> Clone it >> Add Footer and Customize code >> Then make PR >> Send me Screen Shot also.

@minhaj-313 we have to add hover effect in navbar right?

**Comment by minhaj-313** [comment]
> > @amitmishra11 @flow6979 Steps: 1st make Star to this Repository >> Then Fork it >> Clone it >> Add Footer and Customize code >> Then make PR >> Send me Screen Shot also.
> 
> @minhaj-313 we have to add hover effect in navbar right?

Yes
