### ISSUE TITLE
Improve the mobile responsiveness 

### ISSUE THREAD

**Issue by zugzwang03** [minhaj-313/Portfolio-1#90]
In mobile view, the writings on the left gets hidden. I can fix that. Can I work on this issue under hacktoberfest '22?

![Screenshot_20221024-152516_Chrome](https://user-images.githubusercontent.com/95460021/197500762-ceb0d30a-6434-45c9-8d09-6452af566e45.jpg)

**Comment by minhaj-313** [comment]
@zugzwang03 yes you can
